import express from "express";
import { getCurrentUser, getSecurity, getUserById, loginUser, logoutUser, revokeDevice, updateTheme, updateUser } from "../controllers/userController.js";
import { requireFirebaseIdentity, requireSession } from "../middleware/auth.js";
const router = express.Router();
router.post("/login", requireFirebaseIdentity, loginUser);
router.get("/session", requireFirebaseIdentity, requireSession, getCurrentUser);
router.post("/logout", requireSession, logoutUser);
router.patch("/theme", requireSession, updateTheme);
router.get("/security", requireSession, getSecurity);
router.delete("/security/devices/:deviceId", requireSession, revokeDevice);
router.patch("/update/:id", requireSession, updateUser);
router.get("/:id", getUserById);
export default router;
